### ISSUE TITLE
Может обновите скрипт?

### ISSUE THREAD

**Issue by BodyDub** [alexeymalets/nginx-install-auto#1]
Unfortunately, the script is Nginx Install/Upgrade auto Your OS does not support!

OS: Ubuntu Linux 18.04.1

**Comment by alexeymalets** [comment]
Здравствуйте, обновления выйдет в самое ближайшее время. Пожалуйста, следите за версиями.

**Comment by alexeymalets** [comment]
> Unfortunately, the script is Nginx Install/Upgrade auto Your OS does not support!
> 
> OS: Ubuntu Linux 18.04.1
Пожалуйста, предоставьте вывод команды:
#cat /etc/*-release

**Comment by alexeymalets** [comment]
Скрипт обновлен, теперь он поддерживает следующие версии ОС:
* Debian 7,8,9,10
* Ubuntu 12,14,15,16,18
* CentOS/CloudLinux 5,6,7,8
